### ISSUE TITLE
`getPrebuiltLambda()` fails when node is installed in a file path that contains white spaces

### ISSUE THREAD

**Issue by dlaudams** [cdklabs/cdk-ecr-deployment#214]
I have node installed in `C:\Program Files\nodejs\node.exe`

The prebuilt lambda function fails on every build as the exec function is attempting to execute `C:\Program` instead of `C:\Program Files\nodejs\node.exe`.

The impact is the docker image is build on every single run locally, taking more time.

```
  console.log
    Try to get prebuilt lambda

      at getCode (node_modules/cdk-ecr-deployment/src/index.ts:49:15)

  console.log
    "C:\Program Files\nodejs\node.exe" C:\zzz\node_modules\cdk-ecr-deployment\lambda\install.js C:\zzz\node_modules\cdk-ecr-deployment\lambda\out

      at getCode (node_modules/cdk-ecr-deployment/src/index.ts:53:7)

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
  console.warn
    Can not get prebuilt lambda: Error: Command failed: C:\Program Files\nodejs\node.exe C:\zzz\node_modules\cdk-ecr-deployment\lambda\install.js C:\zzz\node_modules\cdk-ecr-deployment\lambda\out
    'C:\Program' is not recognized as an internal or external command,
    operable program or batch file.
```

```typescript
function getPrebuiltLambda(outputDir: string): boolean {
  try {
    console.log('Try to get prebuilt lambda');

    const installScript = path.join(__dirname, '../lambda/install.js');
    child_process.execSync(`${process.argv0} ${installScript} ${outputDir}`);
    return true;
  } catch (err) {
    console.warn(`Can not get prebuilt lambda: ${err}`);
    return false;
  }
}
```

One potential fix is to quote the process parameter:

```typescript
child_process.execFileSync(process.argv0, [installScript, prebuiltPath]);
```

https://github.com/cdklabs/cdk-ecr-deployment/blob/fbeeee17a1f927001ee244cb59ff8ffe0b4c4763/src/index.ts#L164

**Comment by dlaudams** [comment]
The lack of escaping will also cause problems when `__dirname` includes special characters, such as spaces, ampersands, redirects, pipes, etc.
